### ISSUE TITLE
Application onCreate 报错问题

### ISSUE THREAD

**Issue by chenyanmo** [baidao/tinker-manager#21]
Hi：
我先集成tinker sdk 后（正常使用） 再集成 tinker-manager的sdk 后打开app异常 日志如下：

12-14 10:42:57.811 23210-23210/com.xxx D/ResourcesManager: creating new AssetManager and set to /data/app/com.xxx-1/base.apk
12-14 10:42:57.831 23210-23210/com.xxx W/Tinker.TinkerLoader: tryLoadPatchFiles:patch dir not exist:/data/data/com.xxx/tinker
12-14 10:42:57.831 23210-23210/com.xxx D/Tinker.DefaultAppLike: onBaseContextAttached:
12-14 10:42:57.831 23210-23210/com.xxx D/Tinker.DefaultAppLike: onCreate
12-14 10:42:57.841 23210-23210/com.xxx W/Tinker.Tinker: tinker patch directory: /data/data/com.xxx/tinker
12-14 10:42:57.841 23210-23210/com.xxx I/Tinker.TinkerLoadResult: parseTinkerResult loadCode:-2
12-14 10:42:57.841 23210-23210/com.xxx W/Tinker.TinkerLoadResult: can't find patch file, is ok, just return
12-14 10:42:57.841 23210-23210/com.xxx I/Tinker.DefaultLoadReporter: patch load result, path:/data/data/com.xxx/tinker, code:-2, cost:3
12-14 10:42:57.841 23210-23210/com.xxx W/Tinker.Tinker: tinker load fail!
12-14 10:42:57.851 23210-23210/com.xxx D/AndroidRuntime: Shutting down VM
12-14 10:42:57.851 23210-23210/com.xxx E/AndroidRuntime: FATAL EXCEPTION: main
                                                             Process: com.xxx , PID: 23210
                                                             java.lang.RuntimeException: Unable to create application com.xxx.FHApplication: com.tencent.tinker.loader.TinkerRuntimeException: Tinker Exception:onCreate method not found
                                                                 at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5116)
                                                                 at android.app.ActivityThread.access$1600(ActivityThread.java:177)
                                                                 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1509)
                                                                 at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                 at android.os.Looper.loop(Looper.java:145)
                                                                 at android.app.ActivityThread.main(ActivityThread.java:5942)
                                                                 at java.lang.reflect.Method.invoke(Native Method)
                                                                 at java.lang.reflect.Method.invoke(Method.java:372)
                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1400)
                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1195)
                                                              Caused by: com.tencent.tinker.loader.TinkerRuntimeException: Tinker Exception:onCreate method not found
                                                                 at com.tencent.tinker.loader.app.TinkerApplication.delegateMethod(TinkerApplication.java:183)
                                                                 at com.tencent.tinker.loader.app.TinkerApplication.onCreate(TinkerApplication.java:192)
                                                                 at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1020)
                                                                 at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5113)
                                                                 at android.app.ActivityThread.access$1600(ActivityThread.java:177) 
                                                                 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1509) 
                                                                 at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                 at android.os.Looper.loop(Looper.java:145) 
                                                                 at android.app.ActivityThread.main(ActivityThread.java:5942) 
                                                                 at java.lang.reflect.Method.invoke(Native Method) 
                                                                 at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1400) 
                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1195) 
                                                              Caused by: java.lang.reflect.InvocationTargetException
                                                                 at java.lang.reflect.Method.invoke(Native Method)
                                                                 at java.lang.reflect.Method.invoke(Method.java:372)
                                                                 at com.tencent.tinker.loader.app.TinkerApplication.delegateMethod(TinkerApplication.java:181)
                                                                 at com.tencent.tinker.loader.app.TinkerApplication.onCreate(TinkerApplication.java:192) 
                                                                 at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1020) 
                                                                 at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5113) 
                                                                 at android.app.ActivityThread.access$1600(ActivityThread.java:177) 
                                                                 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1509) 
                                                                 at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                 at android.os.Looper.loop(Looper.java:145) 
                                                                 at android.app.ActivityThread.main(ActivityThread.java:5942) 
                                                                 at java.lang.reflect.Method.invoke(Native Method) 
                                                                 at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1400) 
                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1195) 
                                                              Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.pm.PackageManager android.content.Context.getPackageManager()' on a null object reference
                                                                 at android.content.ContextWrapper.getPackageManager(ContextWrapper.java:95)
                                                                 at com.xxx.utils.ChannelUtil.getVersionCode(ChannelUtil.java:151)
                                                                 at com.xxx.utils.ChannelUtil.getChannelFromSP(ChannelUtil.java:129)
                                                                 at com.xxx.utils.ChannelUtil.getChannel(ChannelUtil.java:49)
                                                                 at com.xxx.utils.ChannelUtil.getChannel(ChannelUtil.java:34)
                                                                 at com.xxx.MyApplication.onCreate(MyApplication.java:168)
                                                                 at com.xxx.ApplicationLike.onCreate(ApplicationLike.java:92)
                                                                 at java.lang.reflect.Method.invoke(Native Method) 
                                                                 at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                 at com.tencent.tinker.loader.app.TinkerApplication.delegateMethod(TinkerApplication.java:181) 
                                                                 at com.tencent.tinker.loader.app.TinkerApplication.onCreate(TinkerApplication.java:192) 
                                                                 at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1020) 
                                                                 at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5113) 
                                                                 at android.app.ActivityThread.access$1600(ActivityThread.java:177) 
                                                                 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1509) 
                                                                 at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                 at android.os.Looper.loop(Looper.java:145) 
                                                                 at android.app.ActivityThread.main(ActivityThread.java:5942) 
                                                                 at java.lang.reflect.Method.invoke(Native Method) 
                                                                 at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1400) 
                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1195) 
12-14 10:42:57.851 931-1317/? W/ActivityManager:   Force finishing activity com.xxx/.ui.SplashActivity
12-14 10:42:57.851 931-1317/? D/FocusedStackFrame: Set to : 0
12-14 10:42:57.861 931-23228/? W/DropBoxManagerService: Dropping: data_app_crash (2371 > 0 bytes)
12-14 10:42:57.861 931-1317/? E/ActivityManager: Invalid thumbnail dimensions: 576x576

**Comment by typ0520** [comment]
-2是补丁文件没有加载到，  是不是没有下载成功，补丁文件存储在/sdcard/${包名}/patchsdk下面

**Comment by typ0520** [comment]
错误日志里有一句  Unable to create application com.xxx.FHApplication，你的包名写的对吗

**Comment by chenyanmo** [comment]
对
@SuppressWarnings("unused")
@DefaultLifeCycle(application = "com.xxx.FHApplication",
        flags = ShareConstants.TINKER_ENABLE_ALL,
        loadVerifyFlag = false)
public class MyApplication extends TinkerApplicationLike {

**Comment by chenyanmo** [comment]
还有一个问题 android6.0以上会报权限问题 我把PatchManager.getInstance().init(getApplication() 初始化工作放到 MainActivity 初步更新没有问题，不知道投到产品环境会不会有问题呢?

**Comment by typ0520** [comment]
@chenyanmo 你先确认下报出的权限问题是patchsdk里面申请的权限吗，目前patchsdk只是需要网络和sd卡的读写权限；如果暂时不想处理就把targetSdkVersion设置成< 23的值

**Comment by xingstarx** [comment]
如果要处理的话，应该怎么弄，targetSdkVersion我目前是 25，也不想采用targetSdkVersion< 23这种方案，那么的话，这个初始化操作是否可以挪动到首次启动的Activity呢？或者是作者把getDeviceId()的方法实现替换一下，不要用`telephonyManager.getDeviceId()`,改成`Settings.System.getString(context.getContentResolver(), android.provider.Settings.Secure.ANDROID_ID)`
