### ISSUE TITLE
android6.0以上需要请求READ_PHONE_STATE权限

### ISSUE THREAD

**Issue by xingstarx** [baidao/tinker-manager#33]
```
05-24 00:04:19.062 1752-1752/com.androidkit.demo E/Tinker.TinkerUncaughtExceptionHandler: uncaughtException:Unable to create application com.xxx.demo.DemoApplication: java.lang.SecurityException: getDeviceId: Neither user 10064 nor current process has android.permission.READ_PHONE_STATE.
05-24 00:04:19.062 1752-1752/com.xxx.demo W/Tinker.TinkerUncaughtExceptionHandler: tinker is not loaded
05-24 00:04:19.067 1752-1752/com.xxx.demo E/Tinker.UncaughtHandler: catch exception when loading tinker:java.lang.RuntimeException: Unable to create application com.xxx.demo.DemoApplication: java.lang.SecurityException: getDeviceId: Neither user 10064 nor current process has android.permission.READ_PHONE_STATE.
                                                                               at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5406)
                                                                               at android.app.ActivityThread.-wrap2(ActivityThread.java)
                                                                               at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1545)
                                                                               at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                               at android.os.Looper.loop(Looper.java:154)
                                                                               at android.app.ActivityThread.main(ActivityThread.java:6119)
                                                                               at java.lang.reflect.Method.invoke(Native Method)
                                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
                                                                            Caused by: java.lang.SecurityException: getDeviceId: Neither user 10064 nor current process has android.permission.READ_PHONE_STATE.
                                                                               at android.os.Parcel.readException(Parcel.java:1684)
                                                                               at android.os.Parcel.readException(Parcel.java:1637)
                                                                               at com.android.internal.telephony.ITelephony$Stub$Proxy.getDeviceId(ITelephony.java:4454)
                                                                               at android.telephony.TelephonyManager.getDeviceId(TelephonyManager.java:848)
                                                                               at com.dx168.patchsdk.utils.PatchUtils.getDeviceId(PatchUtils.java:37)
                                                                               at com.dx168.patchsdk.PatchManager.init(PatchManager.java:77)
                                                                               at com.xxx.demo.BaseApplicationLike.onCreate(BaseApplicationLike.java:67)
                                                                               at com.xxx.demo.DemoApplicationLike.onCreate(DemoApplicationLike.java:29)
                                                                               at com.tencent.tinker.loader.app.TinkerApplication.onCreate(TinkerApplication.java:173)
                                                                               at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1024)
                                                                               at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5403)
                                                                               at android.app.ActivityThread.-wrap2(ActivityThread.java) 
                                                                               at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1545) 
                                                                               at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                               at android.os.Looper.loop(Looper.java:154) 
                                                                               at android.app.ActivityThread.main(ActivityThread.java:6119) 
                                                                               at java.lang.reflect.Method.invoke(Native Method) 
                                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886) 
                                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776) 
```

在baseApplicationLike里面的onCreate()方法中，
```java
PatchManager.getInstance().init(getApplication(), "http://192.168.206.176:8080/hotfix-apis/", appId, appSecret, new ActualPatchManager() {
            @Override
            public void patch(Context context, String path) {
                TinkerInstaller.onReceiveUpgradePatch(context, path);
            }

            @Override
            public void cleanPatch(Context context) {
                TinkerInstaller.cleanPatch(context);
            }
        });
```
这个方法内部会调用PatchUtils.getDeviceId方法，这个方法需要先请求运行时权限才能够得到这个唯一的设备id

请问作者有什么好的建议吗？

**Comment by fffffz** [comment]
早就解决了啊，捕获了异常，你看下使用的patchsdk是不是最新的版本

    public static String getDeviceId(Context context) {
        String deviceId;
        try {
            TelephonyManager telephonyManager = (TelephonyManager) context.getSystemService(Context.TELEPHONY_SERVICE);
            deviceId = telephonyManager.getDeviceId();
        } catch (SecurityException e) {
            deviceId = Settings.Secure.getString(context.getContentResolver(), Settings.Secure.ANDROID_ID);
        }
        return TextUtils.isEmpty(deviceId) ? "" : deviceId;
    }

**Comment by xingstarx** [comment]
哦哦，我用的是compile 'com.dx168.patchsdk:patchsdk:1.1.3' 我看最新的是1.1.4了，多谢了啊
